### ISSUE TITLE
Can't join discord.

### ISSUE THREAD

**Issue by yangyueche** [ethernautdao/documentation#7]
Hi, sorry, 
I was trying to join discord channel before, 
but it showed no result, and the error message shows "failed to load messages."
![CleanShot 2021-12-03 at 07 31 55](https://user-images.githubusercontent.com/51125954/144519513-083c3afa-eff2-4d36-a5a3-04fd803a740b.png)
Is there anyway I can do to fix this problem.
Thank you!

**Comment by Dhannte** [comment]
I see you inside the server sorry I missed this error!
